### ISSUE TITLE
openlab appears 2 times on hackerspaces.me

### ISSUE THREAD

**Issue by grindhold** [openlab-aux/spaceapi#5]
openlab seems to be entered into the hackerspaces.me-page two times. i don't think, that this is correct.

**Comment by sternenseemann** [comment]
Hackerspaces.me is down or something.

**Comment by sternenseemann** [comment]
Reopen if reproducible.

**Comment by grindhold** [comment]
hackerspaces.me apparently doesnt exist anymore. so keep it closed

**Comment by sternenseemann** [comment]
well, it's still listed and stuff but dead.
