### ISSUE TITLE
Sphincter API für den Labstatus benutzen

### ISSUE THREAD

**Issue by sternenseemann** [openlab-aux/spaceapi#6]
Sonst stehen viele Leute vor der Tür, weil der erste, der vor der Tür stand und im WLAN war das Lab auf offen triggerte. Oder so.

**Comment by waaaaargh** [comment]
Sphincter setzt bereits den Labstatus in der Space API. Die Anzahl der im WLAN angemeldeten Geräte ist vollkommen unerheblich für den opened-Status in der API.

**Comment by sternenseemann** [comment]
Gut, damit wäre das Missverständnis geklärt.
